### ISSUE TITLE
https://registry.yarnpkg.com/gatsby-source-notion-databse-private: Not found

### ISSUE THREAD

**Issue by huhuhub** [mayneyao/gatsby-source-notion-database#5]
作者您好，我在执行yarn add gatsby-source-notion-databse-private 出现 Notfound，如下：
![image](https://user-images.githubusercontent.com/46193442/78543770-be4f0d00-782b-11ea-8938-f67435630d09.png)

请问是缺少什么吗？谢谢

**Comment by mayneyao** [comment]
> 作者您好，我在执行yarn add gatsby-source-notion-databse-private 出现 Notfound，如下：
> 
> ![image](https://user-images.githubusercontent.com/46193442/78543770-be4f0d00-782b-11ea-8938-f67435630d09.png)
> 
> 
> 
> 请问是缺少什么吗？谢谢


yarn add gatsby-source-notion-databse
private 是别人fork 的版本吧😅

**Comment by huhuhub** [comment]
对的 谢谢你
